// <auto-generated />
using ApiClienteServidor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiClienteServidor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421055115_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("ApiClienteServidor.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persona");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Edad = 28,
                            Nombre = "Juan Pérez"
                        },
                        new
                        {
                            Id = 2,
                            Edad = 34,
                            Nombre = "María Gómez"
                        },
                        new
                        {
                            Id = 3,
                            Edad = 22,
                            Nombre = "Carlos Rodríguez"
                        },
                        new
                        {
                            Id = 4,
                            Edad = 41,
                            Nombre = "Ana López"
                        },
                        new
                        {
                            Id = 5,
                            Edad = 30,
                            Nombre = "Luis Fernández"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
